### PR TITLE
docs: clean up terminology authorization token->access token

### PR DESCRIPTION
**Pull request by andrewbonney**
This addresses a comment received via e-mail about mixed terminology referencing the token used in requests to resource servers.

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by garethsb** [comment]
LGTM

**Comment by lo-simon** [comment]
In nmos_sec_3.png should `2- Bearer Token (Contains auth.token)` be `2- Bearer Token (Contains Access Token)`?

**Comment by andrewbonney** [comment]
Well spotted. I'll adjust.

**Review by lo-simon — APPROVED** [review]
LGTM

**Comment by peterbrightwell** [comment]
Final review on call

**Pull request merged**
